using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

/// <summary>
/// An item in the shop window: a slot (slot layout) or a block over the cells it takes (grid layout). Click selects it,
/// double click or right click buys / sells one. Generated by the window when the skin has no entry prefab; a prefab of
/// your own needs this component - every field is optional.
/// </summary>
[DisallowMultipleComponent]
public class MerchantItemEntryUI : MonoBehaviour, IPointerClickHandler, IPointerEnterHandler, IPointerExitHandler
{
    [SerializeField] private Image background;
    [SerializeField] private Image icon;
    [Tooltip("Optional item name (list-style prefabs).")]
    [SerializeField] private TextMeshProUGUI nameText;
    [SerializeField] private TextMeshProUGUI priceText;
    [Tooltip("Optional backing shown with the price (a dark strip).")]
    [SerializeField] private GameObject priceStrip;
    [SerializeField] private TextMeshProUGUI quantityText;
    [Tooltip("\"Sold out\", \"Bought\", \"Won't buy\"...")]
    [SerializeField] private TextMeshProUGUI badgeText;
    [SerializeField] private GameObject selectedFrame;
    [SerializeField] private GameObject hoverFrame;
    [Tooltip("Fades the entry when it cannot be bought / sold or is filtered out.")]
    [SerializeField] private CanvasGroup group;
    [Tooltip("Tint the background with the skin's slot / grid colours (off for prefabs with their own art).")]
    [SerializeField] private bool tintBackground = true;
    [Tooltip("Scale the texts with the entry's size (generated entries).")]
    [SerializeField] private bool autoFontSize;

    private MerchantWindow owner;
    private MerchantDisplayEntry entry;
    private bool iconDefaultsSaved;
    private Vector2 iconAnchorMin, iconAnchorMax, iconOffsetMin, iconOffsetMax, iconPivot;
    private bool iconPreserve;

    public MerchantDisplayEntry Entry => entry;
    public RectTransform Rect => (RectTransform)transform;

    /// <summary>Wires the parts of a generated entry.</summary>
    public void Configure(Image bg, Image iconImage, TextMeshProUGUI price, GameObject strip, TextMeshProUGUI quantity, TextMeshProUGUI badge,
        GameObject selected, GameObject hover, CanvasGroup canvasGroup)
    {
        background = bg;
        icon = iconImage;
        priceText = price;
        priceStrip = strip;
        quantityText = quantity;
        badgeText = badge;
        selectedFrame = selected;
        hoverFrame = hover;
        group = canvasGroup;
        autoFontSize = true;
    }

    private void Awake()
    {
        if (group == null)
            group = GetComponent<CanvasGroup>();
        SaveIconDefaults();
        if (hoverFrame != null)
            hoverFrame.SetActive(false);
    }

    private void SaveIconDefaults()
    {
        if (iconDefaultsSaved || icon == null)
            return;
        iconDefaultsSaved = true;
        RectTransform r = icon.rectTransform;
        iconAnchorMin = r.anchorMin;
        iconAnchorMax = r.anchorMax;
        iconOffsetMin = r.offsetMin;
        iconOffsetMax = r.offsetMax;
        iconPivot = r.pivot;
        iconPreserve = icon.preserveAspect;
    }

    /// <summary>Shows <paramref name="e"/>. The window sizes and places the entry before calling this.</summary>
    public void Bind(MerchantWindow window, MerchantDisplayEntry e, bool selected, bool grid, MerchantUISkin skin, CurrencyDefinition currency,
        GridInventorySettings gridSettings)
    {
        owner = window;
        entry = e;
        SaveIconDefaults();
        bool empty = e == null || e.IsEmptySlot || e.Item == null;

        if (background != null && tintBackground)
        {
            background.color = empty || !grid ? skin.slotColor : skin.gridItemColor;
            if (skin.slotBackground != null && !grid)
            {
                background.sprite = skin.slotBackground;
                background.type = skin.backgroundImageType;
            }
        }

        if (icon != null)
        {
            icon.enabled = !empty && e.Item.Icon != null;
            if (!empty)
            {
                icon.sprite = e.Item.Icon;
                if (grid)
                    MerchantGridIcon.Layout(icon, e.Item, e.Rotated, Rect.rect.size, gridSettings);
                else
                    RestoreIcon();
            }
        }

        float h = Rect.rect.height;
        float small = autoFontSize ? Mathf.Clamp(h * 0.19f, 10f, 14f) * skin.fontScale : 0f;

        if (nameText != null)
            nameText.text = empty ? "" : e.Item.Name;
        if (quantityText != null)
        {
            string q = "";
            if (!empty)
            {
                if (e.Mode == MerchantTransactionType.Buy)
                    q = e.Unlimited ? "" : e.Quantity > 0 ? $"×{e.Quantity}" : "";
                else if (e.Quantity > 1)
                    q = e.Quantity.ToString();
            }
            quantityText.text = q;
            if (autoFontSize) quantityText.fontSize = small;
        }
        if (priceText != null)
        {
            priceText.text = empty ? "" : (currency != null ? currency.FormatNumber(e.UnitPrice) : e.UnitPrice.ToString());
            priceText.color = !empty && e.Mode == MerchantTransactionType.Buy && !e.Affordable ? skin.unaffordableColor : skin.priceColor;
            bool showPrice = !empty && (e.Available || e.Mode == MerchantTransactionType.Buy);
            priceText.gameObject.SetActive(showPrice);
            if (priceStrip != null) priceStrip.SetActive(showPrice);
            if (autoFontSize) priceText.fontSize = small;
        }
        if (badgeText != null)
        {
            string badge = "";
            if (!empty)
            {
                if (e.Mode == MerchantTransactionType.Buy && e.Slot != null && !e.Slot.InStock) badge = "SOLD OUT";
                else if (e.Mode == MerchantTransactionType.Sell && !e.Available) badge = "✕";
                else if (e.Slot != null && e.Slot.IsBuyback) badge = "SOLD BACK";
            }
            badgeText.text = badge;
            badgeText.gameObject.SetActive(badge.Length > 0);
            if (autoFontSize) badgeText.fontSize = Mathf.Clamp(h * 0.16f, 9f, 13f) * skin.fontScale;
        }
        if (selectedFrame != null)
            selectedFrame.SetActive(selected && !empty);
        if (group != null)
            group.alpha = empty ? 1f : e.Dimmed || !e.Available ? skin.dimmedAlpha : 1f;
    }

    private void RestoreIcon()
    {
        if (!iconDefaultsSaved || icon == null)
            return;
        RectTransform r = icon.rectTransform;
        r.anchorMin = iconAnchorMin;
        r.anchorMax = iconAnchorMax;
        r.pivot = iconPivot;
        r.offsetMin = iconOffsetMin;
        r.offsetMax = iconOffsetMax;
        r.localRotation = Quaternion.identity;
        icon.preserveAspect = iconPreserve;
    }

    public void SetSelected(bool selected)
    {
        if (selectedFrame != null)
            selectedFrame.SetActive(selected && entry != null && !entry.IsEmptySlot);
    }

    public void OnPointerClick(PointerEventData eventData)
    {
        if (owner == null || entry == null || entry.IsEmptySlot || entry.Item == null)
            return;
        owner.OnEntryClicked(entry, eventData.button, eventData.clickCount);
    }

    public void OnPointerEnter(PointerEventData eventData)
    {
        if (hoverFrame != null && entry != null && !entry.IsEmptySlot)
            hoverFrame.SetActive(true);
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        if (hoverFrame != null)
            hoverFrame.SetActive(false);
    }

    private void OnDisable()
    {
        if (hoverFrame != null)
            hoverFrame.SetActive(false);
    }
}

/// <summary>
/// Lays an item's icon over a block of grid cells the way the grid inventory draws its items (<see cref="GridInventoryView"/>):
/// the Grid Icon when the item has one, turned 90° when rotated, stood up by its Grid Icon Angle, fitted by the grid
/// settings' Icon Fit Mode - so shop items look exactly like the same items in the player's grid.
/// </summary>
public static class MerchantGridIcon
{
    public static void Layout(Image icon, ItemSO so, bool rotated, Vector2 blockSize, GridInventorySettings settings)
    {
        if (icon == null)
            return;
        settings = settings ?? new GridInventorySettings();
        RectTransform irt = icon.rectTransform;
        if (so != null && so.GridIcon != null && icon.sprite != so.GridIcon)
            icon.sprite = so.GridIcon;

        // Laid out for the upright shape (W × H cells, minus the padding) and turned 90° with the item.
        float inset = Mathf.Max(0f, settings.iconPadding);
        Vector2 upright = rotated ? new Vector2(blockSize.y, blockSize.x) : blockSize;
        Vector2 area = new Vector2(Mathf.Max(4f, upright.x - inset * 2f), Mathf.Max(4f, upright.y - inset * 2f));
        float angle = so != null && !so.HasGridIcon ? so.GridIconAngle : 0f;
        Vector2 size = area;
        bool keep = settings.iconFitMode == GridIconFit.KeepProportions;
        if (Mathf.Abs(angle) > 0.01f)
        {
            // A picture turned by 'angle' as big as possible along the long side (a diagonal sword stands upright).
            Sprite sp = icon.sprite;
            float aspect = sp != null && sp.rect.height > 0f ? sp.rect.width / sp.rect.height : 1f;
            float rad = angle * Mathf.Deg2Rad, cos = Mathf.Abs(Mathf.Cos(rad)), sin = Mathf.Abs(Mathf.Sin(rad));
            float hByWidth = area.x / (aspect * cos + sin), hByHeight = area.y / (aspect * sin + cos);
            float h = Mathf.Min(area.y >= area.x ? hByHeight : hByWidth, Mathf.Max(area.x, area.y));
            size = new Vector2(h * aspect, h);
            keep = true;
        }
        else if (so != null && so.HasGridIcon)
        {
            keep = true; // drawn for this shape
        }
        irt.anchorMin = irt.anchorMax = new Vector2(0.5f, 0.5f);
        irt.pivot = new Vector2(0.5f, 0.5f);
        irt.anchoredPosition = Vector2.zero;
        irt.sizeDelta = size;
        irt.localRotation = Quaternion.Euler(0f, 0f, (rotated ? 90f : 0f) + angle);
        icon.preserveAspect = keep;
    }
}
