using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// The player's status bars (health, stamina, mana, hunger, thirst...), generated by the inventory UI builder.
/// Each status manager fills its own bar (its UI Image); this component adds the "75 / 100" text and hides a whole row
/// when its manager hides the bar (body heat, oxygen and sleep only show when they matter).
/// </summary>
[DisallowMultipleComponent]
public class StatusBarsUI : MonoBehaviour
{
    [Serializable]
    public class Row
    {
        [Tooltip("The status shown by this row.")]
        public StatusManager status;
        [Tooltip("The bar the status fills (its UI Image).")]
        public Image fill;
        [Tooltip("Optional '75 / 100' text.")]
        public TMP_Text valueText;
        [Tooltip("The row object (label, background, bar, text): hidden while the status hides its bar.")]
        public GameObject row;
    }

    [SerializeField] private List<Row> rows = new List<Row>();
    [Tooltip("Show the current and maximum value on each bar.")]
    [SerializeField] private bool showValues = true;

    public IReadOnlyList<Row> Rows => rows;

    /// <summary>True when a row for this status exists (the builder does not add it twice).</summary>
    public bool HasRow(StatusManager status)
    {
        for (int i = 0; i < rows.Count; i++)
            if (rows[i] != null && rows[i].status == status)
                return true;
        return false;
    }

    public void AddRow(StatusManager status, Image fill, TMP_Text valueText, GameObject row)
    {
        rows.RemoveAll(r => r == null || r.status == null || r.status == status);
        rows.Add(new Row { status = status, fill = fill, valueText = valueText, row = row });
    }

    /// <summary>Drops rows whose status or row object no longer exists (removed duplicates, deleted components).</summary>
    public void RemoveMissingRows()
    {
        rows.RemoveAll(r => r == null || r.status == null || r.row == null);
    }

    private void LateUpdate()
    {
        for (int i = 0; i < rows.Count; i++)
        {
            Row r = rows[i];
            if (r == null || r.row == null)
                continue;
            // Managers that show their bar only when relevant turn the bar object on and off: follow it with the row.
            bool show = r.status != null && (r.fill == null || r.fill.gameObject.activeSelf);
            if (r.row.activeSelf != show)
                r.row.SetActive(show);
            if (show && showValues && r.valueText != null)
            {
                string text = $"{r.status.CurrentValue:0} / {r.status.MaxValue:0}";
                if (r.valueText.text != text)
                    r.valueText.text = text;
            }
        }
    }
}
